#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage :
    path : /
    controller : App\Controller\DefaultController::homepage
    
homepage_translation :
    path : /{_locale}
    controller : App\Controller\DefaultController::homepage
    requirements:
      _locale : 'en|fr'    
    
add_product :
    path : /{_locale}/add/product
    controller : App\Controller\ProductController::addProduct
    requirements:
      _locale : 'en|fr'
      
list_product :
    path : /{_locale}/list/product
    controller : App\Controller\ProductController::list
    defaults:
      _locale: 'en'
    requirements:
      _locale: 'en|fr'
      
display_product:
    path: /{_locale}/display/product
    controller : App\Controller\ProductController::singleDisplay
    defaults:
      _locale: 'en'
    requirements:
      _locale: 'en|fr'        
    
register :
    path : /{_locale}/register
    controller : App\Controller\UserController::register
    requirements:
      _locale : 'en|fr'   
    
user_activate :
    path : /{_locale}/user/activate/{token}
    controller : App\Controller\UserController::activateUser   
    requirements :
      token : '[a-z0-9-]+'
      _locale : 'en|fr'
      
      
user_available :
  path : /user/available
  controller: App\Controller\UserController::usernameExist
  methods: 'POST'
       
login: 
  path: /login
  controller: App\Controller\UserController::login
  
logout:
  path: /logout
    
